tags:
  - slug: ESP32
    name: ESP32
  - slug: LED
    name: LED
  - slug: I/O
    name: I/O
  - slug: Sensor
    name: Sensor
  - slug: OLED Display
    name: OLED Display
  - slug: Web Server
    name: Web Server